### PR TITLE
Simplify js-controller directory resolution

### PR DESCRIPTION
**Pull request by AlCalzone**
Another (JS-only) attempt to solve https://github.com/ioBroker/ioBroker/issues/35

DO NOT MERGE YET, this is currently only a test.

### CODE REVIEW

**Comment by Apollon77** [comment]
/home/travis/build/ioBroker/ioBroker.zwave/tmp/node_modules/iobroker.zwave/lib/utils.js:33
		} catch { /* not found */ }
		        ^
SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/travis/build/ioBroker/ioBroker.zwave/tmp/node_modules/iobroker.zwave/main.js:11:20)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)

**Comment by AlCalzone** [comment]
Woops das war ein Überbleibsel aus typescript

**Comment by AlCalzone** [comment]
The install script hs "npm install --unsafe-perms" somewhere, that should be "npm install --unsafe-perm" without "s"

**Comment by Apollon77** [comment]
I will fix that tomorrow. My fault.

**Comment by AlCalzone** [comment]
> I will fix that tomorrow. My fault.

No more need to ;)

Otherwise I think the changes worked. Question is how do we proceed? Just merge or do we need to do some more tests?

**Comment by Apollon77** [comment]
Merge and make Forum Thread in testers to get community Test too?!

**Comment by AlCalzone** [comment]
Sounds good, will do!

**Comment by Apollon77** [comment]
Additionally @GermanBluefox should Test locally in his environment too. 

If this works too I could push it into all repos and have run all tests and let community test then again with e.g. hm-rpc or an other often used adapter.

**Pull request merged**
