### PR TITLE
Save & restore network layout

### PR DESCRIPTION
**Pull request by carsten19**
Follow-up to the request of restoring the network layout. If the user has a large number of nodes and rearranges them via dragging we store the layout and restore it.

### CODE REVIEW

**Comment by AlCalzone** [comment]
Build errors are false positives. I think we need some kind of retry logic in the travis tests when it decides not to resolve old.openzwave.com for some reason.

**Comment by carsten19** [comment]
Added retry to curl

**Comment by AlCalzone** [comment]
I'm not sure if this will help. Better than nothing of course, but we might have to auto-restart the entire Travis job (including the virtual machine). That can only be done in travis.yml. But thats something for a different PR altogether.

**Comment by carsten19** [comment]
I have seen a user report where the download also failed once so the retry doesn't hurt.
Unfortunately I have no idea what the problem is with the Mac OS build errors.

**Comment by AlCalzone** [comment]
I've just restarted the build again with deleted caches. We'll see if that helps. If not, I don't care :D

**Pull request merged**
