### PR TITLE
omnipotent OpenZWave installation

### PR DESCRIPTION
**Pull request by ekarak**
I ported over parts of the node-openzwave-shared installation script that attempts to locate prior installation of the OpenZwave library, and skips downloading and building it if it's there already. Ideally we should also make use of precompiled packages (deb/rpm/whatever) to speed things up.

### CODE REVIEW

**Comment by ekarak** [comment]
nodeJS 0.10 build failed as I'm using child_process.execSync. Can we deprecate 0.10.x?

**Comment by Apollon77** [comment]
my personal opinion: yes ... From my knowledge all systems/platform should have at least 0.12 available ... Maybe Bluefox has some more details?!

**Comment by Apollon77** [comment]
... but error sare not only because of execSync ...
https://travis-ci.org/ioBroker/ioBroker.zwave/builds/189525969 Fails completely

**Comment by ekarak** [comment]
Looks we're ok now for all the builds except Node.JS 0.10.x
BTW: I've deprecated 0.10.x in the node-openzwave-shared package sometime ago, so this old NodeJS version must be removed anyway from ioBroker.zwave  as well.

**Pull request merged**
