### PR TITLE
Add Patch 1125, needed for CentralScene Support

### PR DESCRIPTION
**Pull request by husky-koglhof**
Added OpenZwave Patch 1125, so we can use CentralScene Support within ioBroker

### CODE REVIEW

**Comment by AlCalzone** [comment]
Does this work for you? https://github.com/OpenZWave/open-zwave/pull/1125 shows it should be merged into the Dev branch of OZW and there it shows merge conflicts. But to be fair, I never actually tried to merge it into the master branch. If it's that easy, that would be nice.

**Comment by husky-koglhof** [comment]
Hello, it works in my development and production environment. This change was developed for a friend of mine, it works there too.
Only the installation routine would have to be adjusted if necessary.
I'll try the next week and maybe make another request.

**Comment by AlCalzone** [comment]
I'll give it a try and see if I can finally use my WallMote with this :)

**Comment by AlCalzone** [comment]
Damn that actually works :)
unbenannt

**Comment by husky-koglhof** [comment]
Hey cool, should I test the installation routine again, or was it ok?
When you will build the new version? Cause friends of me are waiting on this patch.

**Comment by GermanBluefox** [comment]
@husky-koglhof If you still "alive" on github, could you give the access to homekit please?
https://github.com/husky-koglhof/ioBroker.homekit/issues/12

**Comment by AlCalzone** [comment]
IMO we can publish a new version 1.3.0 pretty soon, as it seems to be working for both of us.

**Comment by husky-koglhof** [comment]
Ok, I will test it next week on my development box and give you some information, if it is working correct. After that you can make a new version.

**Comment by husky-koglhof** [comment]
Hi, from my site it's working. Can you please create a new Version? Thanks

**Pull request merged**
