### PR TITLE
Fix issues 75 and 76

### PR DESCRIPTION
**Pull request by carsten19**
Disable physics of the map to fix the moving nodes
Remove cleanup as there is currently no way to distinguish user renames from library changes
Increase version
@Apollon77 please review

### CODE REVIEW

**Comment by Apollon77** [comment]
looks good, we should think about adding an admin-v3 compatible index page too,but this is an other story

**Comment by Apollon77** [comment]
could you please also update io-package with version and news? Thank you!

**Comment by carsten19** [comment]
io-package included
I have also incuded a minor change to the network layout which slightly improves visibility (star shape for controller, boxes for others)

**Comment by carsten19** [comment]
Expanded PR to fix #79

**Comment by carsten19** [comment]
Ready to be merged from my side. The Travis error is due to the URL of the openzwave repo which can't be resolved.

**Comment by Apollon77** [comment]
Hm ... but if travis fails on installing it it will also fail for the users!
I would exect that the zip file is called openzwave-1.6.913.zip but the resulting directory is openzwave-1.6.913 and not open-zwave-openzwave-1.6.913 as from the "cd". So we would need to fix the script or?!

**Comment by Apollon77** [comment]
looks better :-) I wait for it to finish and merge tomorrow

**Comment by Apollon77** [comment]
Thank you very much!

**Comment by carsten19** [comment]
Good catch :) I just reinstalled to be sure - looks good
Nut sure why the build on Mac fails as I did not modify the general statements so it would have already failed before. Maybe zip -u might fix it.

**Comment by arteck** [comment]
const version = 'openzwave-1.6.913'; 

why not master ??

**Comment by carsten19** [comment]
@arteck see issue #79

**Pull request merged**
