### PR TITLE
Add ldconfig and bump ozw version

### PR DESCRIPTION
**Pull request by carsten19**
Bump ozw version and add ldconfig with a reference to the latest fixer

### CODE REVIEW

**Review by AlCalzone — CHANGES_REQUESTED** [review]
I would classify this as a breaking change (major version increase), not a bugfix (patch version bump). So, IMO it should be a 2.0.0 => see also https://forum.iobroker.net/topic/26204/versionierung-von-iobroker-und-adaptern

**Comment by AlCalzone** [comment]
Also, I squash-merged your last PR (didn't notice it was on the master branch). Please use feature branches in the future. To clean this up:
1. Reset your master branch to the upstream:
```
git checkout master
git reset --hard upstream/master
```
2. Restore the commit:
```
git cherry-pick 638dfd6 
```

**Comment by carsten19** [comment]
I agree to the version reasoning but that's probably an overkill for such a small change.
Should I revert the version change for now and keep it as master?

**Comment by AlCalzone** [comment]
The version change is IMO not a breaking change.

Requiring a current fixer version to be able to execute `sudo ldconfig` is. So we could include the bump in a patch release and do another major release with ldconfig.

**Comment by carsten19** [comment]
Reduced the commit to latest openzwave version

**Comment by AlCalzone** [comment]
LGTM

**Comment by AlCalzone** [comment]
Squash-merged, please reset your master branch to the upstream (make sure to stash any new changes or put them on a branch):
```
git fetch upstream
git checkout master
git reset --hard upstream/master
git push -f
```

**Pull request merged**
